### ISSUE TITLE
Odometry Calculation

### ISSUE THREAD

**Issue by tensarflow** [agnunez/espros#10]
Hey I wonder where [this](https://github.com/agnunez/espros/blob/99b3ee93390973853bc1d1aaaf540019c64a119a/EspRos/EspRos.ino#L355) calculation comes from? Specifically why you think that `double th = (current_rmc - current_lmc) / 45. * PI` would calculate the angle, and why `45` ?. I tried your code but didn't get satisfying results.
Do you have any literature for this?

**Comment by agnunez** [comment]
Don't remember well, but I think it was a simplistic solution to estimate the rotation angle Theta,  considering that with the specific used car and encoders, we needed 45 ticks in one wheel, while the other stop, to  rotate 180 deg the car. The rest is just conversion to radians using (180 deg = PI radians). It worked fine in my case
