### ISSUE TITLE
Doesnt compile for esp32 (Nodemcu v2)

### ISSUE THREAD

**Issue by chrissunny94** [agnunez/espros#4]
`Build options changed, rebuilding all
/home/chris/Arduino/espros/EspRos/EspRos.ino:30:25: fatal error: ESP8266WiFi.h: No such file or directory
compilation terminated.
exit status 1
Error compiling for board Node32s.`

**Comment by PawanRao93** [comment]
@chrissunny94 - did you find any solutions for the problem. I am using a NodeMCU - ESP-32S module and as you said, it does not compile and I get the same error. However, when I compile choosing the board to be a "Generic ESP8266 Module" the code compiles with no errors. However, I am unable to talk to the NodeMCU - ESP32 board with the board selected to Generic ESP8266 Module. 

Please let me know in case you found any workaround for this problem. 

@agnunez  - will be very helpful if you can help us with this problem. 

Thanks, 
Pawan Rao

**Comment by akshaykvnit** [comment]
For ESP32, you need to change `#include <ESP8266WiFi.h>` to `#include <WiFi.h>`
