### ISSUE TITLE
Wont compile

### ISSUE THREAD

**Issue by chrissunny94** [agnunez/espros#5]
`'class ArduinoHardware' has no member named 'setConnection'
 nh.getHardware()->setConnection(server, serverPort);
                 ^
exit status 1
'class ArduinoHardware' has no member named 'setConnection'`

**Comment by pdeprost** [comment]
Hello,
Did you find any solution ? I have the same problem.
Tanks

**Comment by chrissunny94** [comment]
The code works properly .
 The problem was with installing the esp drivers , just sort that and you should be ready to go .

**Comment by agnunez** [comment]
Thanks
